### ISSUE TITLE
Enable\Disable Outlines

### ISSUE THREAD

**Issue by IncDD** [cakeslice/Outline-Effect#33]
How to disable Outline when starting a project? And enable if necessary.

**Comment by eobet** [comment]
Yes, this script enables outline components in the editor even if you manually disabled them yourself.

That's really bad form, because it makes it difficult to write your own scripts that enables and disables the effect.

**Comment by iseta** [comment]
Hi, I'm not sure if this is still helpful to anyone, or even to cakeslice itself but a workaround I found on this issue is to comment out everything inside the OnEnable() function inside the OutlineEffect.cs, it seems to work alright now and I can enable/disable in the editor or by scripts whenever I choose. 
![image](https://user-images.githubusercontent.com/17050249/66315039-6589d080-e8eb-11e9-9b17-b1eab21a8414.png)

**Comment by JimmyCushnie** [comment]
Fixed with #43 .
